<?php

namespace Proxies\__CG__\Diff\OrderTripBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orders extends \Diff\OrderTripBundle\Entity\Orders implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'Created', 'userid', 'providedamount', 'finalized', 'pdfName', 'billfilename', 'products');
        }

        return array('__isInitialized__', 'id', 'Created', 'userid', 'providedamount', 'finalized', 'pdfName', 'billfilename', 'products');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orders $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function GetProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'GetProducts', array());

        return parent::GetProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($Created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($Created));

        return parent::setCreated($Created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid($userid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', array($userid));

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', array());

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvidedamount($providedamount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvidedamount', array($providedamount));

        return parent::setProvidedamount($providedamount);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvidedamount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvidedamount', array());

        return parent::getProvidedamount();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalized($finalized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalized', array($finalized));

        return parent::setFinalized($finalized);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalized()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalized', array());

        return parent::getFinalized();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfName($pdfName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfName', array($pdfName));

        return parent::setPdfName($pdfName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfName', array());

        return parent::getPdfName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillfilename($billfilename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillfilename', array($billfilename));

        return parent::setBillfilename($billfilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillfilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillfilename', array());

        return parent::getBillfilename();
    }

}
