order_trip_homepage:
    pattern: /orders
    defaults: { _controller:OrderTripBundle:Order:index }
view_order:
    pattern: /orders/view/{OrderID}/{Finalize}
    defaults: { _controller:OrderTripBundle:Order:view , Finalize:"" }
view_trip:
    pattern: /trips/view/{TripID}/{Finalize}
    defaults: { _controller:OrderTripBundle:Trip:view , Finalize:"" }
trip_homepage:
    pattern: /trips
    defaults: { _controller:OrderTripBundle:Trip:index}
trip_upload:
    pattern: /trips/upload/{TripID}
    defaults: { _controller:OrderTripBundle:Trip:upload ,TripID:0}
finalize_trip:
    pattern: /trips/finalize/{TripID}
    defaults: { _controller:OrderTripBundle:Trip:finalizeTrip }
submit_order_bill:
    pattern: /orders/bill/{OrderID}
    defaults: { _controller:OrderTripBundle:Order:OrderBill }
trip_cerere:
    pattern: /trip/cerere/{TripID}
    defaults: { _controller:OrderTripBundle:Trip:cerere }
trip_declaratie:
    pattern: /trip/declaratie/{TripID}
    defaults: { _controller:OrderTripBundle:Trip:declaratie }
logout_page:
     pattern: /logoutt
     defaults: { _controller: LoginBundle:Login:logout }
trip_user_stats:
     pattern: /usage/trips
     defaults: { _controller: OrderTripBundle:OrderTripUserStats:trip }
order_user_stats:
     pattern: /usage/orders
     defaults: { _controller: OrderTripBundle:OrderTripUserStats:order }
trip_delete:
     pattern: /trips/delete/{TripID}
     defaults: { _controller:OrderTripBundle:Trip:delete }
order_delete:
     pattern: /orders/delete/{OrderID}
     defaults: { _controller:OrderTripBundle:Order:delete }
product_delete:
     pattern: /orders/deleteProduct/{ProductID}/{OrderID}
     defaults: { _controller:OrderTripBundle:Order:deleteProduct ,Finalize:"" }
bill_delete:
     pattern: /bills/delete/{Type}/{ID}/{BillID}
     defaults: { _controller:OrderTripBundle:Bill:delete }
add_order:
     pattern: /orders/add/{OrderID}
     defaults: { _controller:OrderTripBundle:Order:add , OrderID:0 }
add_edit_trip:
     pattern: /trips/add/{TripID}
     defaults: { _controller:OrderTripBundle:Trip:add, TripID:0 }
upload_finallize_trip:
     pattern: /trips/finalize_upload/{TripID}
     defaults: { _controller:OrderTripBundle:Trip:uploadfinalize }
