Diff\OrderTripBundle\Entity\Trips:
    type: entity
    table: trips
    indexes:
        UserID:
            columns:
                - UserID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        startdate:
            type: datetime
            nullable: false
            comment: ''
            column: StartDate
        enddate:
            type: datetime
            nullable: true
            comment: ''
            column: EndDate
        userid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: UserID
        finalize:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
        providedamount:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            default: '0'
            column: ProvidedAmount
        destination:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        flagCerere:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: flag_cerere
        flagDeclaratie:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: flag_declaratie
        flagInvitatie:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: flag_invitatie
        uploadFinalize:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: upload_finalize   
    lifecycleCallbacks: {  }
